import {
  defineToolcraftPerformance,
  type ToolcraftPerformanceConfig,
} from "@/toolcraft/runtime";

/* 1000-block feature-length SRT (50k+ chars): the heaviest realistic caption
   upload, shared by the load profile and browser stress tests. */
const heavyCaptionFixture = Array.from(
  { length: 1000 },
  (_, index) =>
    `${index + 1}\n00:${String(Math.floor(index / 60)).padStart(2, "0")}:${String(index % 60).padStart(2, "0")},000 --> 00:${String(Math.floor((index + 1) / 60)).padStart(2, "0")}:${String((index + 1) % 60).padStart(2, "0")},000\nSpeaker: Caption block ${index + 1} with enough words to wrap.`,
).join("\n\n");

/* The product renderer is DOM text over one decoded background image (or a
   pattern tile) at 1080×1350/1920 — low primitive count, so DOM stays the
   preview strategy and export repaints the slide through a Canvas 2D painter. */
export const appPerformance: ToolcraftPerformanceConfig = defineToolcraftPerformance({
  browserCheckPolicy: {
    fallbackRunner: "playwright",
    fallbackWhen: ["agent-browser-unavailable", "ci"],
    preferredRunner: "agent-browser",
  },
  rendererPipeline: {
    interactionInvalidation: [
      {
        interaction: "control-change",
        invalidates: ["slide-dom"],
        mustNotInvalidate: ["export-raster"],
        targets: [
          "post.template",
          "post.colourway",
          "scene.source",
          "scene.illustration",
          "content.episode",
          "content.cover.presents",
          "content.cover.title",
          "content.quote.dialogue",
          "content.synopsis.body",
          "content.streaming.lines",
          "content.credits.list",
          "export.includeBackground",
        ],
      },
      {
        interaction: "control-drag",
        invalidates: ["slide-dom"],
        mustNotInvalidate: ["export-raster"],
        targets: ["scene.imagePosition", "scene.imageZoom"],
      },
      {
        interaction: "media-import",
        invalidates: ["slide-dom"],
        targets: ["scene.upload", "audiogram.audio", "audiogram.captions"],
      },
      {
        interaction: "timeline-playback",
        invalidates: ["audiogram-caption"],
        mustNotInvalidate: ["slide-dom", "export-raster"],
        targets: ["timeline.currentTime"],
      },
      {
        interaction: "export",
        invalidates: ["export-raster"],
        targets: [
          "export.image.format",
          "export.image.resolution",
          "export.video.format",
          "export.video.resolution",
        ],
      },
      {
        interaction: "viewport-zoom",
        invalidates: [],
        mustNotInvalidate: ["slide-dom", "export-raster"],
        targets: ["canvas.viewport"],
      },
    ],
    passes: [
      {
        cacheKey: ["runtime-values", "media-assets"],
        id: "slide-dom",
        inputs: ["runtime-values", "media-assets"],
        invalidatedBy: ["control-change", "control-drag", "media-import"],
        kind: "text-layout",
        output: "preview",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["caption-blocks"],
        id: "audiogram-caption",
        inputs: ["caption-blocks", "timeline-time"],
        invalidatedBy: ["timeline-playback", "media-import"],
        kind: "composite",
        output: "preview",
        quality: "full",
        runsOn: "main",
      },
      {
        cacheKey: ["decoded-images", "loaded-fonts"],
        id: "export-raster",
        inputs: ["slide-dom"],
        invalidatedBy: ["export"],
        kind: "export",
        output: "export",
        quality: "export",
        runsOn: "main",
      },
    ],
  },
  rendererStrategy: "dom",
  rendererTechnique: {
    exportRenderer: "canvas-2d",
    fidelityRisks: [
      "The Canvas 2D export painter re-implements the DOM template layout; text wrapping and spacing must be kept in sync with templates.tsx.",
      "Export text drawing needs document.fonts.load for ABC Marist before painting or glyphs fall back to system serif.",
    ],
    layers: [
      {
        content: ["bitmap-media", "dense-pattern"],
        exportMode: "included",
        id: "slide-ground",
        kind: "background",
        primitiveCount: "low",
        renderer: "dom",
        uiSelector: "[data-mm-post-frame]",
      },
      {
        content: ["text"],
        exportMode: "included",
        id: "slide-copy",
        kind: "product-foreground",
        primitiveCount: "low",
        renderer: "dom",
        uiSelector: "#mm-post-slide [data-toolcraft-product-text]",
      },
    ],
    performanceRisks: [
      "Decoded 5000px illustrations are the heaviest preview input; they render as one cover-cropped img element.",
      "8K export rasterises an 8192px-long-edge canvas on the main thread.",
    ],
    previewExportDifferenceReason:
      "Preview shows live DOM for native text fidelity; export repaints the slide with a Canvas 2D painter because Chromium taints canvases for SVG-foreignObject snapshots, so DOM markup cannot be rasterised directly.",
    previewRenderer: "dom",
    productRepresentation: "mixed",
    rendererStrategy: "dom",
    rendererWorkload: "simple-composition",
    sourceRepresentation: "dom-text",
    whyNotAlternativeStrategies: [
      "Canvas 2D preview would rasterise brand typography and lose native text fidelity for a low-count layout that DOM handles within budget.",
      "WebGL/WebGPU is unwarranted: the slide is one image, one pattern tile, and a handful of text nodes — no dense pixel work in preview.",
    ],
  },
  rendererWorkload: "simple-composition",
  scenarios: [
    {
      automated: true,
      automatedTestName: "performance: post.template scenario is declared",
      browser: true,
      browserTestName: "browser perf: post.template change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Template",
      expectedObservable:
        "Changing post.template re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "post-template-change",
      interaction: "control-change",
      target: "post.template",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: content.episode scenario is declared",
      browser: true,
      browserTestName: "browser perf: content.episode change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Episode",
      expectedObservable:
        "Changing content.episode re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "content-episode-change",
      interaction: "control-change",
      target: "content.episode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: content.cover.presents scenario is declared",
      browser: true,
      browserTestName: "browser perf: content.cover.presents change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Label",
      expectedObservable:
        "Changing content.cover.presents re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "content-cover-presents-change",
      interaction: "control-change",
      target: "content.cover.presents",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: content.cover.title scenario is declared",
      browser: true,
      browserTestName: "browser perf: content.cover.title change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Title",
      expectedObservable:
        "Changing content.cover.title re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "content-cover-title-change",
      interaction: "control-change",
      target: "content.cover.title",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: content.quote.dialogue scenario is declared",
      browser: true,
      browserTestName: "browser perf: content.quote.dialogue change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Dialogue",
      expectedObservable:
        "Changing content.quote.dialogue re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "content-quote-dialogue-change",
      interaction: "control-change",
      target: "content.quote.dialogue",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: content.synopsis.body scenario is declared",
      browser: true,
      browserTestName: "browser perf: content.synopsis.body change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Body",
      expectedObservable:
        "Changing content.synopsis.body re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "content-synopsis-body-change",
      interaction: "control-change",
      target: "content.synopsis.body",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: content.streaming.lines scenario is declared",
      browser: true,
      browserTestName: "browser perf: content.streaming.lines change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Outro",
      expectedObservable:
        "Changing content.streaming.lines re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "content-streaming-lines-change",
      interaction: "control-change",
      target: "content.streaming.lines",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: content.credits.list scenario is declared",
      browser: true,
      browserTestName: "browser perf: content.credits.list change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Credits",
      expectedObservable:
        "Changing content.credits.list re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "content-credits-list-change",
      interaction: "control-change",
      target: "content.credits.list",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: post.colourway scenario is declared",
      browser: true,
      browserTestName: "browser perf: post.colourway change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Colourway",
      expectedObservable:
        "Changing post.colourway re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "post-colourway-change",
      interaction: "control-change",
      target: "post.colourway",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: audiogram.guestColourway scenario is declared",
      browser: true,
      browserTestName: "browser perf: audiogram.guestColourway change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Guest colourway",
      expectedObservable:
        "Changing the guest colourway reblends the audiogram ground crossfade within the responsiveness budget.",
      fixture: "Audiogram template with a two-speaker SRT fixture.",
      id: "audiogram-guest-colourway-change",
      interaction: "control-change",
      target: "audiogram.guestColourway",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: scene.source scenario is declared",
      browser: true,
      browserTestName: "browser perf: scene.source change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Scene",
      expectedObservable:
        "Changing scene.source re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "scene-source-change",
      interaction: "control-change",
      target: "scene.source",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: export.includeBackground scenario is declared",
      browser: true,
      browserTestName: "browser perf: export.includeBackground change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Include",
      expectedObservable:
        "Changing export.includeBackground re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "export-includeBackground-change",
      interaction: "control-change",
      target: "export.includeBackground",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: appearance.background scenario is declared",
      browser: true,
      browserTestName: "browser perf: appearance.background change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Background colour",
      expectedObservable:
        "Changing appearance.background re-renders the slide within the responsiveness budget.",
      fixture: "Default cover post with the control's template branch active.",
      id: "appearance-background-change",
      interaction: "control-change",
      target: "appearance.background",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: carousel.episode scenario is declared",
      browser: true,
      browserTestName: "browser perf: carousel.episode change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Episode set",
      expectedObservable:
        "Changing the episode set selection updates runtime state within budget.",
      fixture: "Default cover post.",
      id: "carousel-episode-change",
      interaction: "control-change",
      target: "carousel.episode",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: carousel.slides scenario is declared",
      browser: true,
      browserTestName: "browser perf: carousel slide actions stay within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1000, maxLongTaskMs: 200 },
      controlLabel: "Slides",
      expectedObservable:
        "Adding a slide or building the episode set commits new layers within budget.",
      fixture: "Default cover post with no slide layers.",
      id: "carousel-slides-actions",
      interaction: "control-change",
      target: "carousel.slides",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: on-canvas image crop stays responsive",
      browser: true,
      browserTestName: "browser perf: dragging the image crop stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500, maxLongTaskMs: 200 },
      expectedObservable:
        "Dragging on the preview image live-moves the crop within budget without frame gaps.",
      fixture: "Cover slide with an episode illustration as the scene source.",
      id: "scene-image-crop-stability",
      interaction: "viewport-stability",
      target: "scene.imagePosition",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: scene.illustration scenario is declared",
      browser: true,
      browserTestName: "browser perf: scene.illustration change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500, maxLongTaskMs: 200 },
      controlLabel: "Episode",
      expectedObservable:
        "Switching to the heaviest illustration decodes and renders within budget.",
      fixture: "Illustration scene source with the heaviest bundled artwork.",
      id: "illustration-workload",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 5263, width: 5000 },
          metric: "media-area",
          smoothTarget: { height: 5263, width: 5000 },
          smoothTargetRatio: 1,
          target: "scene.illustration",
          userFacingRange: "fully-guaranteed",
        },
        reason: "E3 is the heaviest bundled illustration (5000\u00d75263 JPEG).",
        value: { height: 5263, width: 5000 },
      },
      target: "scene.illustration",
      values: { default: "ep1", max: "ep3", min: "ep1" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "performance: export.image.format scenario is declared",
      browser: true,
      browserTestName: "browser perf: export.image.format change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Format",
      expectedObservable:
        "Switching the export format updates runtime state within budget.",
      fixture: "Default cover post.",
      id: "format-workload",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "jpg",
          metric: "custom",
          smoothTarget: "jpg",
          smoothTargetRatio: 1,
          target: "export.image.format",
          userFacingRange: "fully-guaranteed",
        },
        reason: "JPG is the heavier encode path for the export canvas.",
        value: "jpg",
      },
      target: "export.image.format",
      values: { default: "png", max: "jpg", min: "png" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "performance: on-canvas image zoom stays responsive",
      browser: true,
      browserTestName: "browser perf: the under-image zoom slider stays responsive",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500, maxLongTaskMs: 200 },
      expectedObservable:
        "Dragging the under-image zoom slider rescales the illustration within budget without frame gaps.",
      fixture: "Cover slide with an episode illustration as the scene source.",
      id: "scene-image-zoom-stability",
      interaction: "control-drag",
      target: "scene.imageZoom",
      uiSelector: "[data-scene-zoom]",
      workload: false,
    },
    {
      automated: true,
      automatedTestName:
        "performance: stress preview budget is declared for the largest slide",
      browser: true,
      browserTestName:
        "browser perf: preview render stays within budget at the largest canvas",
      budget: { maxLongTaskMs: 200, maxPreviewMs: 2000 },
      expectedObservable:
        "The slide preview renders within budget at the story canvas with the heaviest illustration.",
      fixture: "Story canvas (1080\u00d71920) with the heaviest illustration and longest copy.",
      id: "preview-render-stress",
      interaction: "preview-render",
      stress: true,
      // Stress-only scenario: the heavy baseline is the fixture pair below.
      stressFixture: {
        kind: "large-canvas",
        loadProfile: {
          hardLimit: { height: 1920, width: 1080 },
          metric: "canvas-area",
          smoothTarget: { height: 1920, width: 1080 },
          smoothTargetRatio: 1,
          target: "canvas.size",
          userFacingRange: "fully-guaranteed",
        },
        reason: "The story canvas is the largest product output size.",
        value: { height: 1920, width: 1080 },
      },
      workload: false,
      workloadFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 5263, width: 5000 },
          metric: "media-area",
          smoothTarget: { height: 5263, width: 5000 },
          smoothTargetRatio: 1,
          target: "scene.illustration",
          userFacingRange: "fully-guaranteed",
        },
        reason: "The heaviest decoded illustration exercises the preview pass.",
        value: { height: 5263, width: 5000 },
      },
    },
    {
      automated: true,
      automatedTestName:
        "performance: viewport stability budget is declared for the slide canvas",
      browser: true,
      browserTestName:
        "browser perf: canvas pan and zoom stay stable with a rendered slide",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500 },
      expectedObservable:
        "Canvas pan/zoom keeps the slide steady with no unexpected viewport jumps.",
      fixture: "Cover slide with an episode illustration as the scene source.",
      id: "viewport-stability",
      interaction: "viewport-stability",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 5263, width: 5000 },
          metric: "media-area",
          smoothTarget: { height: 5263, width: 5000 },
          smoothTargetRatio: 1,
          target: "scene.illustration",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Viewport interactions must stay smooth with the decoded illustration.",
        value: { height: 5263, width: 5000 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: viewport zoom stress budget is declared",
      browser: true,
      browserTestName: "browser perf: canvas zoom keeps frame gaps within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500, maxLongTaskMs: 200 },
      expectedObservable:
        "Repeated canvas zoom keeps frame gaps and long tasks within budget.",
      fixture: "Cover slide with the heaviest illustration while zooming the canvas.",
      id: "viewport-zoom-stress",
      interaction: "viewport-zoom-stress",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 5263, width: 5000 },
          metric: "media-area",
          smoothTarget: { height: 5263, width: 5000 },
          smoothTargetRatio: 1,
          target: "scene.illustration",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Zoom must stay smooth with the heaviest decoded illustration.",
        value: { height: 5263, width: 5000 },
      },
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: filmstrip interactions budget is declared",
      browser: true,
      browserTestName: "browser perf: carousel filmstrip interactions keep the canvas stable",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1500, maxLongTaskMs: 200 },
      expectedObservable:
        "Filmstrip slide selection and reorder keep the rendered slide and viewport stable within budget.",
      fixture: "Episode set built so five carousel slides exist.",
      id: "filmstrip-interactions-stability",
      interaction: "viewport-stability",
      target: "carousel.slides",
      workload: false,
    },
    {
      automated: true,
      automatedTestName: "performance: media import budget is declared for scene uploads",
      browser: true,
      browserTestName: "browser perf: uploading a large image decodes within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxPreviewMs: 2000 },
      expectedObservable:
        "A 1920×1080-equivalent upload decodes and renders as the slide ground within budget.",
      fixture: "Scene source set to upload.",
      id: "scene-media-import",
      interaction: "media-import",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 1080, width: 1920 },
          metric: "media-area",
          smoothTarget: { height: 1080, width: 1920 },
          smoothTargetRatio: 1,
          target: "scene.upload",
          userFacingRange: "fully-guaranteed",
        },
        reason: "A 1920\u00d71080 upload is the realistic heavy import.",
        value: { height: 1080, width: 1920 },
      },
      target: "scene.upload",
      values: {
        default: { height: 1080, width: 1920 },
        max: { height: 1080, width: 1920 },
        min: { height: 1080, width: 1920 },
      },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 1080, width: 1920 },
          metric: "media-area",
          smoothTarget: { height: 1080, width: 1920 },
          smoothTargetRatio: 1,
          target: "scene.upload",
          userFacingRange: "fully-guaranteed",
        },
        minCount: 1,
        reason: "Media imports must be tested with at least a 1920×1080 image.",
        value: { height: 1080, width: 1920 },
      },
    },
    {
      automated: true,
      automatedTestName: "performance: scene.upload scenario is declared",
      browser: true,
      browserTestName: "browser perf: scene.upload change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 200 },
      controlLabel: "Image",
      expectedObservable:
        "Attaching an uploaded image renders it as the slide ground within budget.",
      fixture: "Scene source set to upload with a 1920x1080 image.",
      id: "upload-workload",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 1080, width: 1920 },
          metric: "media-area",
          smoothTarget: { height: 1080, width: 1920 },
          smoothTargetRatio: 1,
          target: "scene.upload",
          userFacingRange: "fully-guaranteed",
        },
        reason: "A 1920x1080 upload is the realistic heavy attachment.",
        value: { height: 1080, width: 1920 },
      },
      target: "scene.upload",
      values: {
        default: { height: 1080, width: 1920 },
        max: { height: 1080, width: 1920 },
        min: { height: 256, width: 256 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "performance: export.image.resolution scenario is declared",
      browser: true,
      browserTestName: "browser perf: export.image.resolution change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Resolution",
      expectedObservable:
        "Switching export resolution updates runtime state within budget.",
      fixture: "Default cover post.",
      id: "resolution-workload",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the heaviest export raster preset.",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "current" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "performance: audiogram.audio scenario is declared",
      browser: true,
      browserTestName: "browser perf: audiogram.audio change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 2000, maxLongTaskMs: 200 },
      controlLabel: "Audio",
      expectedObservable:
        "Attaching episode audio decodes metadata and sets the timeline duration within budget.",
      fixture: "Audiogram template with a short test tone.",
      id: "audiogram-audio-workload",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 1, width: 5292000 },
          metric: "custom",
          smoothTarget: { height: 1, width: 5292000 },
          smoothTargetRatio: 1,
          target: "audiogram.audio",
          userFacingRange: "fully-guaranteed",
        },
        reason: "A two-minute 44.1kHz audio file is the realistic heavy source.",
        value: { height: 1, width: 5292000 },
      },
      target: "audiogram.audio",
      values: {
        default: { height: 1, width: 5292000 },
        max: { height: 1, width: 5292000 },
        min: { height: 1, width: 44100 },
      },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "performance: audiogram.captions scenario is declared",
      browser: true,
      browserTestName: "browser perf: audiogram.captions change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 1000, maxLongTaskMs: 200 },
      controlLabel: "Captions",
      expectedObservable:
        "Attaching an SRT parses caption blocks and renders the active caption within budget.",
      fixture: "Audiogram template with a 200-block SRT.",
      id: "audiogram-captions-workload",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "large-text",
        loadProfile: {
          hardLimit: heavyCaptionFixture,
          metric: "text-length",
          smoothTarget: heavyCaptionFixture,
          smoothTargetRatio: 1,
          target: "audiogram.captions",
          userFacingRange: "fully-guaranteed",
        },
        minChars: 50000,
        minLines: 1000,
        reason:
          "A 1000-block feature-length SRT (50k+ characters) is the heaviest realistic caption file.",
        value: heavyCaptionFixture,
      },
      target: "audiogram.captions",
      values: { default: 20, max: 1000, min: 2 },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "performance: export.video.format scenario is declared",
      browser: true,
      browserTestName: "browser perf: export.video.format change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Format",
      expectedObservable:
        "Choosing the video format updates runtime state within budget.",
      fixture: "Audiogram template active.",
      id: "video-format-workload",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "mp4",
          metric: "custom",
          smoothTarget: "mp4",
          smoothTargetRatio: 1,
          target: "export.video.format",
          userFacingRange: "fully-guaranteed",
        },
        reason: "MP4 is the WebCodecs container used for delivery.",
        value: "mp4",
      },
      target: "export.video.format",
      values: { default: "mp4", max: "mp4", min: "mp4" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "performance: export.video.resolution scenario is declared",
      browser: true,
      browserTestName: "browser perf: export.video.resolution change stays within budget",
      budget: { maxFrameGapMs: 120, maxInteractionMs: 500, maxLongTaskMs: 200 },
      controlLabel: "Resolution",
      expectedObservable:
        "Choosing the video resolution updates runtime state within budget.",
      fixture: "Audiogram template active.",
      id: "video-resolution-workload",
      interaction: "control-change",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "4k",
          metric: "custom",
          smoothTarget: "4k",
          smoothTargetRatio: 1,
          target: "export.video.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "4K is the heaviest encoded frame size.",
        value: "4k",
      },
      target: "export.video.resolution",
      values: { default: "current", max: "4k", min: "current" },
      workload: true,
    },
    {
      automated: true,
      automatedTestName: "performance: export budget is declared for 8K PNG delivery",
      browser: true,
      browserTestName: "browser perf: 8K PNG export completes within budget",
      budget: { maxExportMs: 8000 },
      expectedObservable:
        "An 8K PNG export resolves with correct dimensions inside the export budget.",
      fixture: "Cover slide with illustration scene at 8K export resolution.",
      id: "png-export-8k",
      interaction: "export-copy",
      stress: true,
      stressFixture: {
        kind: "max-value",
        loadProfile: {
          hardLimit: "8k",
          metric: "custom",
          smoothTarget: "8k",
          smoothTargetRatio: 1,
          target: "export.image.resolution",
          userFacingRange: "fully-guaranteed",
        },
        reason: "8K is the largest exported raster (8192px long edge).",
        value: "8k",
      },
      target: "export.image.resolution",
      values: { default: "4k", max: "8k", min: "current" },
      workload: true,
      workloadFixture: {
        kind: "media",
        loadProfile: {
          hardLimit: { height: 5263, width: 5000 },
          metric: "media-area",
          smoothTarget: { height: 5263, width: 5000 },
          smoothTargetRatio: 1,
          target: "scene.illustration",
          userFacingRange: "fully-guaranteed",
        },
        reason: "Export must rasterise the heaviest decoded illustration.",
        value: { height: 5263, width: 5000 },
      },
    },
  ],
  usesCustomRenderer: true,
  workloadTargets: [
    "scene.illustration",
    "scene.upload",
    "export.image.format",
    "export.image.resolution",
    "audiogram.audio",
    "audiogram.captions",
    "export.video.format",
    "export.video.resolution",
  ],
});
